project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card:
    creator: "@nathanhubens"
    site: "@fasterai"
  open-graph: true
  repo-actions: [issue]
  page-footer: "&copy; By Nathan Hubens"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Report an Issue"
        icon: bug
        href: https://github.com/FasterAI-Labs/fasterbench/issues
    right:
      - icon: github
        href: "https://github.com/FasterAI-Labs/fasterbench"

  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - index.ipynb
      - section: Tutorials
        contents:
        - tutorials/benchmark.ipynb
        - tutorials/profiling.ipynb
        - tutorials/roofline.ipynb
        - tutorials/report.ipynb
      - section: Core
        contents:
        - core/core.ipynb
        - core/utils.ipynb
      - section: Metrics
        contents:
        - metrics/size.ipynb
        - metrics/speed.ipynb
        - metrics/compute.ipynb
        - metrics/memory.ipynb
        - metrics/energy.ipynb
      - section: Analysis
        contents:
        - analysis/benchmark.ipynb
        - analysis/profiling.ipynb
        - analysis/roofline.ipynb
        - analysis/report.ipynb
      - section: Visualization
        contents:
        - visualization/plot.ipynb

metadata-files: [nbdev.yml]
